import type { CfbGame, WeeklySlate } from "./types";

function team(
  id: string,
  displayName: string,
  shortName: string,
  abbreviation: string,
  rank: number | null,
  wins: number,
  losses: number
) {
  return { id, displayName, shortName, abbreviation, rank, wins, losses, logo: null };
}

// Illustrative-only slate used when the live ESPN scoreboard can't be reached.
// Matchups, records, and lines are fictional and should never be treated as real.
const SAMPLE_GAMES: CfbGame[] = [
  {
    id: "sample-1",
    startDate: "2026-09-05T23:30:00Z",
    shortName: "MICH @ OSU",
    venue: "Ohio Stadium",
    broadcast: "ABC",
    neutralSite: false,
    conferenceGame: true,
    home: team("sample-osu", "Ohio State Buckeyes", "Ohio State", "OSU", 2, 3, 0),
    away: team("sample-mich", "Michigan Wolverines", "Michigan", "MICH", 8, 3, 0),
    odds: { provider: "Sample", spread: -6.5, favorite: "home", overUnder: 47.5, homeMoneyline: -260, awayMoneyline: 215 },
    statusDetail: "Sat, Sep 5 · 7:30 PM ET",
    completed: false,
    homeScore: null,
    awayScore: null,
  },
  {
    id: "sample-2",
    startDate: "2026-09-05T19:00:00Z",
    shortName: "ALA @ GA",
    venue: "Sanford Stadium",
    broadcast: "CBS",
    neutralSite: false,
    conferenceGame: true,
    home: team("sample-uga", "Georgia Bulldogs", "Georgia", "UGA", 1, 3, 0),
    away: team("sample-bama", "Alabama Crimson Tide", "Alabama", "ALA", 4, 2, 1),
    odds: { provider: "Sample", spread: -3, favorite: "home", overUnder: 44.5, homeMoneyline: -155, awayMoneyline: 132 },
    statusDetail: "Sat, Sep 5 · 3:00 PM ET",
    completed: false,
    homeScore: null,
    awayScore: null,
  },
  {
    id: "sample-3",
    startDate: "2026-09-06T00:00:00Z",
    shortName: "TROY @ TEX",
    venue: "DKR Memorial Stadium",
    broadcast: "LHN",
    neutralSite: false,
    conferenceGame: false,
    home: team("sample-tex", "Texas Longhorns", "Texas", "TEX", 3, 3, 0),
    away: team("sample-troy", "Troy Trojans", "Troy", "TROY", null, 2, 1),
    odds: { provider: "Sample", spread: -27.5, favorite: "home", overUnder: 55.5, homeMoneyline: -3500, awayMoneyline: 1400 },
    statusDetail: "Sat, Sep 5 · 8:00 PM ET",
    completed: false,
    homeScore: null,
    awayScore: null,
  },
  {
    id: "sample-4",
    startDate: "2026-09-05T16:00:00Z",
    shortName: "DUKE @ ND",
    venue: "Notre Dame Stadium",
    broadcast: "NBC",
    neutralSite: false,
    conferenceGame: false,
    home: team("sample-nd", "Notre Dame Fighting Irish", "Notre Dame", "ND", 10, 2, 1),
    away: team("sample-duke", "Duke Blue Devils", "Duke", "DUKE", 22, 3, 0),
    odds: { provider: "Sample", spread: -4.5, favorite: "home", overUnder: 51, homeMoneyline: -180, awayMoneyline: 155 },
    statusDetail: "Sat, Sep 5 · 12:00 PM ET",
    completed: false,
    homeScore: null,
    awayScore: null,
  },
  {
    id: "sample-5",
    startDate: "2026-09-05T20:00:00Z",
    shortName: "ISU @ K-ST",
    venue: "Bill Snyder Family Stadium",
    broadcast: "FOX",
    neutralSite: false,
    conferenceGame: true,
    home: team("sample-kst", "Kansas State Wildcats", "Kansas State", "K-ST", 15, 2, 1),
    away: team("sample-isu", "Iowa State Cyclones", "Iowa State", "ISU", 18, 3, 0),
    odds: { provider: "Sample", spread: 1.5, favorite: "away", overUnder: 46, homeMoneyline: 105, awayMoneyline: -125 },
    statusDetail: "Sat, Sep 5 · 4:00 PM ET",
    completed: false,
    homeScore: null,
    awayScore: null,
  },
  {
    id: "sample-6",
    startDate: "2026-09-05T17:00:00Z",
    shortName: "SMU @ CLEM",
    venue: "Memorial Stadium",
    broadcast: "ESPN",
    neutralSite: false,
    conferenceGame: true,
    home: team("sample-clem", "Clemson Tigers", "Clemson", "CLEM", 9, 3, 0),
    away: team("sample-smu", "SMU Mustangs", "SMU", "SMU", 20, 2, 1),
    odds: { provider: "Sample", spread: -3.5, favorite: "home", overUnder: 49.5, homeMoneyline: -165, awayMoneyline: 142 },
    statusDetail: "Sat, Sep 5 · 1:00 PM ET",
    completed: false,
    homeScore: null,
    awayScore: null,
  },
  {
    id: "sample-7",
    startDate: "2026-09-05T21:30:00Z",
    shortName: "RICE @ LSU",
    venue: "Tiger Stadium",
    broadcast: "SEC Network",
    neutralSite: false,
    conferenceGame: false,
    home: team("sample-lsu", "LSU Tigers", "LSU", "LSU", 6, 3, 0),
    away: team("sample-rice", "Rice Owls", "Rice", "RICE", null, 1, 2),
    odds: { provider: "Sample", spread: -24, favorite: "home", overUnder: 58, homeMoneyline: -2200, awayMoneyline: 950 },
    statusDetail: "Sat, Sep 5 · 5:30 PM ET",
    completed: false,
    homeScore: null,
    awayScore: null,
  },
  {
    id: "sample-8",
    startDate: "2026-09-05T18:00:00Z",
    shortName: "ARIZ @ UTAH",
    venue: "Rice-Eccles Stadium",
    broadcast: "CBS Sports Network",
    neutralSite: false,
    conferenceGame: true,
    home: team("sample-utah", "Utah Utes", "Utah", "UTAH", 24, 2, 1),
    away: team("sample-ariz", "Arizona Wildcats", "Arizona", "ARIZ", null, 2, 1),
    odds: { provider: "Sample", spread: -6, favorite: "home", overUnder: 43.5, homeMoneyline: -230, awayMoneyline: 195 },
    statusDetail: "Sat, Sep 5 · 2:00 PM ET",
    completed: false,
    homeScore: null,
    awayScore: null,
  },
];

export function getSampleSlate(week: number, seasonYear: number): WeeklySlate {
  return {
    week,
    seasonYear,
    seasonType: 2,
    games: SAMPLE_GAMES,
    source: "sample",
    asOf: new Date().toISOString(),
  };
}
