import type { Fundamentals } from "./types";

/**
 * Static reference fundamentals used when a live provider is unavailable
 * (no network access, no API key configured, or the ticker isn't covered
 * by the live provider). Figures are approximate illustrative snapshots,
 * not real-time data — always prefer a live fetch when one succeeds.
 *
 * Margins are fractions (0.42 = 42%). Revenue and market cap are in USD.
 */
export const FALLBACK_FUNDAMENTALS: Record<string, Omit<Fundamentals, "ticker" | "source">> = {
  AAPL: { name: "Apple Inc.", sector: "Technology", industry: "Consumer Electronics", assetType: "Equity", price: 230, marketCap: 3.5e12, peRatio: 35, grossMargin: 0.46, operatingMargin: 0.31, profitMargin: 0.26, revenueTTM: 400e9, revenueGrowthYoY: 0.06, dividendYield: 0.004, beta: 1.2, asOf: "static reference" },
  MSFT: { name: "Microsoft Corp.", sector: "Technology", industry: "Software - Infrastructure", assetType: "Equity", price: 470, marketCap: 3.5e12, peRatio: 37, grossMargin: 0.69, operatingMargin: 0.45, profitMargin: 0.36, revenueTTM: 270e9, revenueGrowthYoY: 0.15, dividendYield: 0.007, beta: 0.9, asOf: "static reference" },
  GOOGL: { name: "Alphabet Inc.", sector: "Communication Services", industry: "Internet Content & Information", assetType: "Equity", price: 195, marketCap: 2.4e12, peRatio: 27, grossMargin: 0.58, operatingMargin: 0.34, profitMargin: 0.29, revenueTTM: 350e9, revenueGrowthYoY: 0.13, dividendYield: 0.004, beta: 1.05, asOf: "static reference" },
  GOOG: { name: "Alphabet Inc.", sector: "Communication Services", industry: "Internet Content & Information", assetType: "Equity", price: 197, marketCap: 2.4e12, peRatio: 27, grossMargin: 0.58, operatingMargin: 0.34, profitMargin: 0.29, revenueTTM: 350e9, revenueGrowthYoY: 0.13, dividendYield: 0.004, beta: 1.05, asOf: "static reference" },
  AMZN: { name: "Amazon.com Inc.", sector: "Consumer Cyclical", industry: "Internet Retail", assetType: "Equity", price: 225, marketCap: 2.4e12, peRatio: 40, grossMargin: 0.49, operatingMargin: 0.11, profitMargin: 0.08, revenueTTM: 650e9, revenueGrowthYoY: 0.11, dividendYield: 0, beta: 1.15, asOf: "static reference" },
  META: { name: "Meta Platforms Inc.", sector: "Communication Services", industry: "Internet Content & Information", assetType: "Equity", price: 620, marketCap: 1.6e12, peRatio: 28, grossMargin: 0.82, operatingMargin: 0.43, profitMargin: 0.36, revenueTTM: 165e9, revenueGrowthYoY: 0.19, dividendYield: 0.003, beta: 1.2, asOf: "static reference" },
  NVDA: { name: "NVIDIA Corp.", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 175, marketCap: 4.2e12, peRatio: 55, grossMargin: 0.75, operatingMargin: 0.63, profitMargin: 0.55, revenueTTM: 165e9, revenueGrowthYoY: 0.7, dividendYield: 0.0003, beta: 1.7, asOf: "static reference" },
  TSLA: { name: "Tesla Inc.", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "Equity", price: 260, marketCap: 830e9, peRatio: 90, grossMargin: 0.18, operatingMargin: 0.07, profitMargin: 0.06, revenueTTM: 95e9, revenueGrowthYoY: 0.02, dividendYield: 0, beta: 2.1, asOf: "static reference" },
  AVGO: { name: "Broadcom Inc.", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 220, marketCap: 1.05e12, peRatio: 38, grossMargin: 0.65, operatingMargin: 0.4, profitMargin: 0.33, revenueTTM: 55e9, revenueGrowthYoY: 0.3, dividendYield: 0.013, beta: 1.1, asOf: "static reference" },
  AMD: { name: "Advanced Micro Devices", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 165, marketCap: 265e9, peRatio: 45, grossMargin: 0.5, operatingMargin: 0.1, profitMargin: 0.06, revenueTTM: 26e9, revenueGrowthYoY: 0.14, dividendYield: 0, beta: 1.8, asOf: "static reference" },
  NFLX: { name: "Netflix Inc.", sector: "Communication Services", industry: "Entertainment", assetType: "Equity", price: 700, marketCap: 300e9, peRatio: 40, grossMargin: 0.47, operatingMargin: 0.27, profitMargin: 0.22, revenueTTM: 38e9, revenueGrowthYoY: 0.15, dividendYield: 0, beta: 1.3, asOf: "static reference" },
  CRM: { name: "Salesforce Inc.", sector: "Technology", industry: "Software - Application", assetType: "Equity", price: 260, marketCap: 250e9, peRatio: 30, grossMargin: 0.76, operatingMargin: 0.19, profitMargin: 0.16, revenueTTM: 36e9, revenueGrowthYoY: 0.09, dividendYield: 0.005, beta: 1.15, asOf: "static reference" },
  ORCL: { name: "Oracle Corp.", sector: "Technology", industry: "Software - Infrastructure", assetType: "Equity", price: 145, marketCap: 400e9, peRatio: 30, grossMargin: 0.71, operatingMargin: 0.3, profitMargin: 0.2, revenueTTM: 55e9, revenueGrowthYoY: 0.08, dividendYield: 0.011, beta: 1.0, asOf: "static reference" },
  ADBE: { name: "Adobe Inc.", sector: "Technology", industry: "Software - Application", assetType: "Equity", price: 400, marketCap: 175e9, peRatio: 25, grossMargin: 0.89, operatingMargin: 0.34, profitMargin: 0.28, revenueTTM: 22e9, revenueGrowthYoY: 0.1, dividendYield: 0, beta: 1.1, asOf: "static reference" },
  INTC: { name: "Intel Corp.", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 24, marketCap: 105e9, peRatio: null, grossMargin: 0.32, operatingMargin: -0.05, profitMargin: -0.1, revenueTTM: 53e9, revenueGrowthYoY: -0.02, dividendYield: 0, beta: 1.1, asOf: "static reference" },
  CSCO: { name: "Cisco Systems Inc.", sector: "Technology", industry: "Communication Equipment", assetType: "Equity", price: 58, marketCap: 230e9, peRatio: 22, grossMargin: 0.64, operatingMargin: 0.26, profitMargin: 0.2, revenueTTM: 55e9, revenueGrowthYoY: 0.05, dividendYield: 0.025, beta: 0.85, asOf: "static reference" },

  JPM: { name: "JPMorgan Chase & Co.", sector: "Financial Services", industry: "Banks - Diversified", assetType: "Equity", price: 235, marketCap: 660e9, peRatio: 13, grossMargin: null, operatingMargin: 0.42, profitMargin: 0.34, revenueTTM: 165e9, revenueGrowthYoY: 0.1, dividendYield: 0.021, beta: 1.1, asOf: "static reference" },
  BAC: { name: "Bank of America Corp.", sector: "Financial Services", industry: "Banks - Diversified", assetType: "Equity", price: 42, marketCap: 320e9, peRatio: 13, grossMargin: null, operatingMargin: 0.33, profitMargin: 0.27, revenueTTM: 100e9, revenueGrowthYoY: 0.05, dividendYield: 0.025, beta: 1.25, asOf: "static reference" },
  WFC: { name: "Wells Fargo & Co.", sector: "Financial Services", industry: "Banks - Diversified", assetType: "Equity", price: 72, marketCap: 240e9, peRatio: 13, grossMargin: null, operatingMargin: 0.33, profitMargin: 0.26, revenueTTM: 82e9, revenueGrowthYoY: 0.03, dividendYield: 0.022, beta: 1.1, asOf: "static reference" },
  GS: { name: "Goldman Sachs Group", sector: "Financial Services", industry: "Capital Markets", assetType: "Equity", price: 560, marketCap: 185e9, peRatio: 15, grossMargin: null, operatingMargin: 0.38, profitMargin: 0.28, revenueTTM: 53e9, revenueGrowthYoY: 0.15, dividendYield: 0.02, beta: 1.3, asOf: "static reference" },
  V: { name: "Visa Inc.", sector: "Financial Services", industry: "Credit Services", assetType: "Equity", price: 310, marketCap: 610e9, peRatio: 30, grossMargin: 0.97, operatingMargin: 0.67, profitMargin: 0.53, revenueTTM: 36e9, revenueGrowthYoY: 0.1, dividendYield: 0.007, beta: 0.95, asOf: "static reference" },
  MA: { name: "Mastercard Inc.", sector: "Financial Services", industry: "Credit Services", assetType: "Equity", price: 520, marketCap: 480e9, peRatio: 34, grossMargin: 0.76, operatingMargin: 0.58, profitMargin: 0.46, revenueTTM: 28e9, revenueGrowthYoY: 0.12, dividendYield: 0.005, beta: 1.05, asOf: "static reference" },
  BRK: { name: "Berkshire Hathaway", sector: "Financial Services", industry: "Insurance - Diversified", assetType: "Equity", price: 470, marketCap: 1.0e12, peRatio: 12, grossMargin: null, operatingMargin: 0.2, profitMargin: 0.18, revenueTTM: 370e9, revenueGrowthYoY: 0.03, dividendYield: 0, beta: 0.85, asOf: "static reference" },

  UNH: { name: "UnitedHealth Group", sector: "Healthcare", industry: "Healthcare Plans", assetType: "Equity", price: 340, marketCap: 310e9, peRatio: 14, grossMargin: 0.24, operatingMargin: 0.07, profitMargin: 0.04, revenueTTM: 400e9, revenueGrowthYoY: 0.07, dividendYield: 0.024, beta: 0.6, asOf: "static reference" },
  JNJ: { name: "Johnson & Johnson", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "Equity", price: 160, marketCap: 385e9, peRatio: 16, grossMargin: 0.68, operatingMargin: 0.24, profitMargin: 0.2, revenueTTM: 89e9, revenueGrowthYoY: 0.04, dividendYield: 0.032, beta: 0.5, asOf: "static reference" },
  LLY: { name: "Eli Lilly and Co.", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "Equity", price: 850, marketCap: 800e9, peRatio: 55, grossMargin: 0.81, operatingMargin: 0.35, profitMargin: 0.28, revenueTTM: 50e9, revenueGrowthYoY: 0.35, dividendYield: 0.007, beta: 0.4, asOf: "static reference" },
  PFE: { name: "Pfizer Inc.", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "Equity", price: 26, marketCap: 150e9, peRatio: 14, grossMargin: 0.65, operatingMargin: 0.15, profitMargin: 0.1, revenueTTM: 60e9, revenueGrowthYoY: -0.03, dividendYield: 0.065, beta: 0.55, asOf: "static reference" },
  ABBV: { name: "AbbVie Inc.", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "Equity", price: 190, marketCap: 335e9, peRatio: 32, grossMargin: 0.7, operatingMargin: 0.28, profitMargin: 0.15, revenueTTM: 56e9, revenueGrowthYoY: 0.05, dividendYield: 0.033, beta: 0.6, asOf: "static reference" },

  WMT: { name: "Walmart Inc.", sector: "Consumer Defensive", industry: "Discount Stores", assetType: "Equity", price: 90, marketCap: 725e9, peRatio: 38, grossMargin: 0.25, operatingMargin: 0.045, profitMargin: 0.03, revenueTTM: 680e9, revenueGrowthYoY: 0.06, dividendYield: 0.009, beta: 0.5, asOf: "static reference" },
  COST: { name: "Costco Wholesale Corp.", sector: "Consumer Defensive", industry: "Discount Stores", assetType: "Equity", price: 950, marketCap: 420e9, peRatio: 52, grossMargin: 0.13, operatingMargin: 0.036, profitMargin: 0.027, revenueTTM: 265e9, revenueGrowthYoY: 0.07, dividendYield: 0.005, beta: 0.75, asOf: "static reference" },
  PG: { name: "Procter & Gamble", sector: "Consumer Defensive", industry: "Household & Personal Products", assetType: "Equity", price: 165, marketCap: 390e9, peRatio: 25, grossMargin: 0.52, operatingMargin: 0.23, profitMargin: 0.18, revenueTTM: 84e9, revenueGrowthYoY: 0.03, dividendYield: 0.024, beta: 0.4, asOf: "static reference" },
  KO: { name: "Coca-Cola Co.", sector: "Consumer Defensive", industry: "Beverages - Non-Alcoholic", assetType: "Equity", price: 70, marketCap: 300e9, peRatio: 24, grossMargin: 0.6, operatingMargin: 0.29, profitMargin: 0.23, revenueTTM: 46e9, revenueGrowthYoY: 0.04, dividendYield: 0.029, beta: 0.55, asOf: "static reference" },
  PEP: { name: "PepsiCo Inc.", sector: "Consumer Defensive", industry: "Beverages - Non-Alcoholic", assetType: "Equity", price: 150, marketCap: 205e9, peRatio: 20, grossMargin: 0.55, operatingMargin: 0.14, profitMargin: 0.1, revenueTTM: 92e9, revenueGrowthYoY: 0.02, dividendYield: 0.036, beta: 0.5, asOf: "static reference" },
  MCD: { name: "McDonald's Corp.", sector: "Consumer Cyclical", industry: "Restaurants", assetType: "Equity", price: 300, marketCap: 215e9, peRatio: 25, grossMargin: 0.57, operatingMargin: 0.46, profitMargin: 0.33, revenueTTM: 26e9, revenueGrowthYoY: 0.03, dividendYield: 0.023, beta: 0.6, asOf: "static reference" },
  NKE: { name: "Nike Inc.", sector: "Consumer Cyclical", industry: "Footwear & Accessories", assetType: "Equity", price: 75, marketCap: 110e9, peRatio: 24, grossMargin: 0.44, operatingMargin: 0.08, profitMargin: 0.06, revenueTTM: 47e9, revenueGrowthYoY: -0.05, dividendYield: 0.019, beta: 1.05, asOf: "static reference" },
  SBUX: { name: "Starbucks Corp.", sector: "Consumer Cyclical", industry: "Restaurants", assetType: "Equity", price: 95, marketCap: 108e9, peRatio: 30, grossMargin: 0.28, operatingMargin: 0.1, profitMargin: 0.07, revenueTTM: 36e9, revenueGrowthYoY: 0.01, dividendYield: 0.025, beta: 0.9, asOf: "static reference" },
  HD: { name: "Home Depot Inc.", sector: "Consumer Cyclical", industry: "Home Improvement Retail", assetType: "Equity", price: 400, marketCap: 400e9, peRatio: 26, grossMargin: 0.33, operatingMargin: 0.14, profitMargin: 0.1, revenueTTM: 160e9, revenueGrowthYoY: 0.04, dividendYield: 0.022, beta: 1.0, asOf: "static reference" },

  XOM: { name: "Exxon Mobil Corp.", sector: "Energy", industry: "Oil & Gas Integrated", assetType: "Equity", price: 115, marketCap: 500e9, peRatio: 14, grossMargin: null, operatingMargin: 0.14, profitMargin: 0.1, revenueTTM: 340e9, revenueGrowthYoY: -0.02, dividendYield: 0.033, beta: 0.9, asOf: "static reference" },
  CVX: { name: "Chevron Corp.", sector: "Energy", industry: "Oil & Gas Integrated", assetType: "Equity", price: 160, marketCap: 300e9, peRatio: 15, grossMargin: null, operatingMargin: 0.12, profitMargin: 0.09, revenueTTM: 195e9, revenueGrowthYoY: -0.03, dividendYield: 0.041, beta: 1.0, asOf: "static reference" },

  BA: { name: "Boeing Co.", sector: "Industrials", industry: "Aerospace & Defense", assetType: "Equity", price: 175, marketCap: 130e9, peRatio: null, grossMargin: 0.1, operatingMargin: -0.08, profitMargin: -0.1, revenueTTM: 68e9, revenueGrowthYoY: 0.1, dividendYield: 0, beta: 1.4, asOf: "static reference" },
  CAT: { name: "Caterpillar Inc.", sector: "Industrials", industry: "Farm & Heavy Construction Machinery", assetType: "Equity", price: 400, marketCap: 195e9, peRatio: 18, grossMargin: 0.34, operatingMargin: 0.2, profitMargin: 0.15, revenueTTM: 63e9, revenueGrowthYoY: 0.0, dividendYield: 0.015, beta: 1.1, asOf: "static reference" },
  GE: { name: "GE Aerospace", sector: "Industrials", industry: "Aerospace & Defense", assetType: "Equity", price: 210, marketCap: 230e9, peRatio: 40, grossMargin: 0.28, operatingMargin: 0.17, profitMargin: 0.14, revenueTTM: 38e9, revenueGrowthYoY: 0.1, dividendYield: 0.006, beta: 1.2, asOf: "static reference" },

  PLTR: { name: "Palantir Technologies", sector: "Technology", industry: "Software - Infrastructure", assetType: "Equity", price: 45, marketCap: 105e9, peRatio: 90, grossMargin: 0.8, operatingMargin: 0.1, profitMargin: 0.16, revenueTTM: 2.9e9, revenueGrowthYoY: 0.27, dividendYield: 0, beta: 2.5, asOf: "static reference" },
  UBER: { name: "Uber Technologies", sector: "Technology", industry: "Software - Application", assetType: "Equity", price: 75, marketCap: 155e9, peRatio: 15, grossMargin: 0.39, operatingMargin: 0.07, profitMargin: 0.2, revenueTTM: 44e9, revenueGrowthYoY: 0.16, dividendYield: 0, beta: 1.4, asOf: "static reference" },
  SHOP: { name: "Shopify Inc.", sector: "Technology", industry: "Software - Application", assetType: "Equity", price: 80, marketCap: 100e9, peRatio: 65, grossMargin: 0.51, operatingMargin: 0.1, profitMargin: 0.08, revenueTTM: 8.9e9, revenueGrowthYoY: 0.25, dividendYield: 0, beta: 2.2, asOf: "static reference" },
  SQ: { name: "Block Inc.", sector: "Technology", industry: "Software - Infrastructure", assetType: "Equity", price: 70, marketCap: 40e9, peRatio: 20, grossMargin: 0.38, operatingMargin: 0.06, profitMargin: 0.05, revenueTTM: 24e9, revenueGrowthYoY: 0.05, dividendYield: 0, beta: 2.4, asOf: "static reference" },
  PYPL: { name: "PayPal Holdings", sector: "Financial Services", industry: "Credit Services", assetType: "Equity", price: 70, marketCap: 68e9, peRatio: 15, grossMargin: 0.46, operatingMargin: 0.18, profitMargin: 0.14, revenueTTM: 32e9, revenueGrowthYoY: 0.06, dividendYield: 0, beta: 1.4, asOf: "static reference" },
  COIN: { name: "Coinbase Global", sector: "Financial Services", industry: "Capital Markets", assetType: "Equity", price: 250, marketCap: 62e9, peRatio: 30, grossMargin: 0.85, operatingMargin: 0.25, profitMargin: 0.3, revenueTTM: 6.5e9, revenueGrowthYoY: 0.4, dividendYield: 0, beta: 3.5, asOf: "static reference" },
  SOFI: { name: "SoFi Technologies", sector: "Financial Services", industry: "Credit Services", assetType: "Equity", price: 15, marketCap: 16e9, peRatio: 35, grossMargin: 0.6, operatingMargin: 0.08, profitMargin: 0.07, revenueTTM: 2.7e9, revenueGrowthYoY: 0.25, dividendYield: 0, beta: 1.9, asOf: "static reference" },

  DIS: { name: "Walt Disney Co.", sector: "Communication Services", industry: "Entertainment", assetType: "Equity", price: 110, marketCap: 200e9, peRatio: 20, grossMargin: 0.34, operatingMargin: 0.13, profitMargin: 0.09, revenueTTM: 92e9, revenueGrowthYoY: 0.04, dividendYield: 0.01, beta: 1.2, asOf: "static reference" },
  T: { name: "AT&T Inc.", sector: "Communication Services", industry: "Telecom Services", assetType: "Equity", price: 24, marketCap: 175e9, peRatio: 13, grossMargin: 0.6, operatingMargin: 0.18, profitMargin: 0.1, revenueTTM: 122e9, revenueGrowthYoY: 0.01, dividendYield: 0.045, beta: 0.6, asOf: "static reference" },

  QCOM: { name: "Qualcomm Inc.", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 165, marketCap: 185e9, peRatio: 18, grossMargin: 0.56, operatingMargin: 0.3, profitMargin: 0.25, revenueTTM: 39e9, revenueGrowthYoY: 0.1, dividendYield: 0.02, beta: 1.3, asOf: "static reference" },
  TXN: { name: "Texas Instruments", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 200, marketCap: 180e9, peRatio: 32, grossMargin: 0.58, operatingMargin: 0.35, profitMargin: 0.3, revenueTTM: 16.5e9, revenueGrowthYoY: 0.08, dividendYield: 0.026, beta: 1.0, asOf: "static reference" },
  MU: { name: "Micron Technology", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 110, marketCap: 125e9, peRatio: 20, grossMargin: 0.38, operatingMargin: 0.22, profitMargin: 0.18, revenueTTM: 28e9, revenueGrowthYoY: 0.6, dividendYield: 0.004, beta: 1.6, asOf: "static reference" },
  IBM: { name: "IBM Corp.", sector: "Technology", industry: "Information Technology Services", assetType: "Equity", price: 230, marketCap: 210e9, peRatio: 28, grossMargin: 0.56, operatingMargin: 0.17, profitMargin: 0.12, revenueTTM: 62e9, revenueGrowthYoY: 0.03, dividendYield: 0.03, beta: 0.7, asOf: "static reference" },

  RIVN: { name: "Rivian Automotive", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "Equity", price: 14, marketCap: 14e9, peRatio: null, grossMargin: -0.05, operatingMargin: -0.5, profitMargin: -0.55, revenueTTM: 5.2e9, revenueGrowthYoY: 0.1, dividendYield: 0, beta: 2.0, asOf: "static reference" },
  F: { name: "Ford Motor Co.", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "Equity", price: 11, marketCap: 43e9, peRatio: 9, grossMargin: 0.08, operatingMargin: 0.03, profitMargin: 0.015, revenueTTM: 180e9, revenueGrowthYoY: 0.03, dividendYield: 0.055, beta: 1.4, asOf: "static reference" },
  GM: { name: "General Motors Co.", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "Equity", price: 55, marketCap: 55e9, peRatio: 6, grossMargin: 0.12, operatingMargin: 0.08, profitMargin: 0.06, revenueTTM: 185e9, revenueGrowthYoY: 0.02, dividendYield: 0.01, beta: 1.5, asOf: "static reference" },

  // Broad-market / sector ETFs — top holdings are approximate, for overlap detection only.
  VOO: { name: "Vanguard S&P 500 ETF", sector: "Diversified", industry: "Large Blend ETF", assetType: "ETF", price: 560, marketCap: null, peRatio: 26, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.012, beta: 1.0, topHoldings: ["AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "AVGO", "TSLA", "BRK"], asOf: "static reference" },
  SPY: { name: "SPDR S&P 500 ETF Trust", sector: "Diversified", industry: "Large Blend ETF", assetType: "ETF", price: 570, marketCap: null, peRatio: 26, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.012, beta: 1.0, topHoldings: ["AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "AVGO", "TSLA", "BRK"], asOf: "static reference" },
  IVV: { name: "iShares Core S&P 500 ETF", sector: "Diversified", industry: "Large Blend ETF", assetType: "ETF", price: 570, marketCap: null, peRatio: 26, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.012, beta: 1.0, topHoldings: ["AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "AVGO", "TSLA", "BRK"], asOf: "static reference" },
  VTI: { name: "Vanguard Total Stock Market ETF", sector: "Diversified", industry: "Total Market ETF", assetType: "ETF", price: 290, marketCap: null, peRatio: 25, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.012, beta: 1.0, topHoldings: ["AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "AVGO", "TSLA", "BRK"], asOf: "static reference" },
  QQQ: { name: "Invesco QQQ Trust (Nasdaq-100)", sector: "Diversified", industry: "Large Growth ETF", assetType: "ETF", price: 500, marketCap: null, peRatio: 32, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.006, beta: 1.1, topHoldings: ["AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "AVGO", "TSLA", "COST"], asOf: "static reference" },
  VUG: { name: "Vanguard Growth ETF", sector: "Diversified", industry: "Large Growth ETF", assetType: "ETF", price: 400, marketCap: null, peRatio: 31, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.005, beta: 1.1, topHoldings: ["AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "AVGO", "TSLA", "LLY"], asOf: "static reference" },
  SCHD: { name: "Schwab US Dividend Equity ETF", sector: "Diversified", industry: "Dividend Value ETF", assetType: "ETF", price: 28, marketCap: null, peRatio: 15, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.035, beta: 0.8, topHoldings: ["PFE", "CVX", "KO", "PEP", "T", "XOM"], asOf: "static reference" },
  VYM: { name: "Vanguard High Dividend Yield ETF", sector: "Diversified", industry: "Dividend Value ETF", assetType: "ETF", price: 135, marketCap: null, peRatio: 17, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.028, beta: 0.85, topHoldings: ["JPM", "XOM", "JNJ", "PG", "CVX", "KO"], asOf: "static reference" },
  DIA: { name: "SPDR Dow Jones Industrial Average ETF", sector: "Diversified", industry: "Large Blend ETF", assetType: "ETF", price: 420, marketCap: null, peRatio: 24, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.018, beta: 0.95, topHoldings: ["GS", "MSFT", "CAT", "V", "HD", "MCD"], asOf: "static reference" },
  ARKK: { name: "ARK Innovation ETF", sector: "Diversified", industry: "Growth / Thematic ETF", assetType: "ETF", price: 55, marketCap: null, peRatio: null, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0, beta: 1.8, topHoldings: ["TSLA", "COIN", "ROKU", "SHOP", "RBLX"], asOf: "static reference" },
  XLK: { name: "Technology Select Sector SPDR", sector: "Technology", industry: "Technology Sector ETF", assetType: "ETF", price: 240, marketCap: null, peRatio: 32, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.007, beta: 1.1, topHoldings: ["AAPL", "MSFT", "NVDA", "AVGO", "CRM", "ORCL"], asOf: "static reference" },
  XLF: { name: "Financial Select Sector SPDR", sector: "Financial Services", industry: "Financial Sector ETF", assetType: "ETF", price: 52, marketCap: null, peRatio: 16, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.017, beta: 1.1, topHoldings: ["JPM", "BRK", "V", "MA", "BAC", "GS", "WFC"], asOf: "static reference" },
};

export function getFallbackFundamentals(ticker: string): Fundamentals | null {
  const entry = FALLBACK_FUNDAMENTALS[ticker.toUpperCase()];
  if (!entry) return null;
  return { ticker: ticker.toUpperCase(), source: "fallback", ...entry };
}
