import type { Fundamentals } from "./types";

/**
 * Static reference fundamentals used when a live provider is unavailable
 * (no network access, no API key configured, or the ticker isn't covered
 * by the live provider). Figures are approximate illustrative snapshots,
 * not real-time data — always prefer a live fetch when one succeeds.
 *
 * Margins are fractions (0.42 = 42%). Revenue and market cap are in USD.
 */
export const FALLBACK_FUNDAMENTALS: Record<string, Omit<Fundamentals, "ticker" | "source">> = {
  AAPL: { name: "Apple Inc.", sector: "Technology", industry: "Consumer Electronics", assetType: "Equity", price: 319.99, marketCap: 4669998058000, peRatio: 36.68, grossMargin: 0.4691, operatingMargin: null, profitMargin: 0.2692, revenueTTM: 416161000000, revenueGrowthYoY: 0.0643, dividendYield: 0.0033, beta: 1.2, asOf: "static reference" },
  MSFT: { name: "Microsoft Corp.", sector: "Technology", industry: "Software - Infrastructure", assetType: "Equity", price: 499.68, marketCap: 3710398824000, peRatio: 27.85, grossMargin: 0.6794, operatingMargin: null, profitMargin: 0.4031, revenueTTM: 331839000000, revenueGrowthYoY: 0.1779, dividendYield: 0.0073, beta: 0.9, asOf: "static reference" },
  GOOGL: { name: "Alphabet Inc.", sector: "Communication Services", industry: "Internet Content & Information", assetType: "Equity", price: 195, marketCap: 2.4e12, peRatio: 27, grossMargin: 0.58, operatingMargin: 0.34, profitMargin: 0.29, revenueTTM: 350e9, revenueGrowthYoY: 0.13, dividendYield: 0.004, beta: 1.05, asOf: "static reference" },
  GOOG: { name: "Alphabet Inc.", sector: "Communication Services", industry: "Internet Content & Information", assetType: "Equity", price: 197, marketCap: 2.4e12, peRatio: 27, grossMargin: 0.58, operatingMargin: 0.34, profitMargin: 0.29, revenueTTM: 350e9, revenueGrowthYoY: 0.13, dividendYield: 0.004, beta: 1.05, asOf: "static reference" },
  AMZN: { name: "Amazon.com Inc.", sector: "Consumer Cyclical", industry: "Internet Retail", assetType: "Equity", price: 225, marketCap: 2.4e12, peRatio: 40, grossMargin: 0.49, operatingMargin: 0.11, profitMargin: 0.08, revenueTTM: 650e9, revenueGrowthYoY: 0.11, dividendYield: 0, beta: 1.15, asOf: "static reference" },
  META: { name: "Meta Platforms Inc.", sector: "Communication Services", industry: "Internet Content & Information", assetType: "Equity", price: 620, marketCap: 1.6e12, peRatio: 28, grossMargin: 0.82, operatingMargin: 0.43, profitMargin: 0.36, revenueTTM: 165e9, revenueGrowthYoY: 0.19, dividendYield: 0.003, beta: 1.2, asOf: "static reference" },
  NVDA: { name: "NVIDIA Corp.", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 230.345, marketCap: 5666095413500, peRatio: 29.12, grossMargin: 0.7107, operatingMargin: null, profitMargin: 0.556, revenueTTM: 215938000000, revenueGrowthYoY: 0.6548, dividendYield: 0.0012, beta: 1.7, asOf: "static reference" },
  TSLA: { name: "Tesla Inc.", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "Equity", price: 353.95, marketCap: 1397942827545, peRatio: 328.98, grossMargin: 0.1803, operatingMargin: null, profitMargin: 0.04, revenueTTM: 94827000000, revenueGrowthYoY: -0.0293, dividendYield: 0, beta: 2.1, asOf: "static reference" },
  AVGO: { name: "Broadcom Inc.", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 220, marketCap: 1.05e12, peRatio: 38, grossMargin: 0.65, operatingMargin: 0.4, profitMargin: 0.33, revenueTTM: 55e9, revenueGrowthYoY: 0.3, dividendYield: 0.013, beta: 1.1, asOf: "static reference" },
  AMD: { name: "Advanced Micro Devices", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 477.45, marketCap: 779427576000, peRatio: 122.56, grossMargin: 0.4951, operatingMargin: null, profitMargin: 0.1251, revenueTTM: 34639000000, revenueGrowthYoY: 0.3433, dividendYield: 0, beta: 1.8, asOf: "static reference" },
  NFLX: { name: "Netflix Inc.", sector: "Communication Services", industry: "Entertainment", assetType: "Equity", price: 700, marketCap: 300e9, peRatio: 40, grossMargin: 0.47, operatingMargin: 0.27, profitMargin: 0.22, revenueTTM: 38e9, revenueGrowthYoY: 0.15, dividendYield: 0, beta: 1.3, asOf: "static reference" },
  CRM: { name: "Salesforce Inc.", sector: "Technology", industry: "Software - Application", assetType: "Equity", price: 260, marketCap: 250e9, peRatio: 30, grossMargin: 0.76, operatingMargin: 0.19, profitMargin: 0.16, revenueTTM: 36e9, revenueGrowthYoY: 0.09, dividendYield: 0.005, beta: 1.15, asOf: "static reference" },
  ORCL: { name: "Oracle Corp.", sector: "Technology", industry: "Software - Infrastructure", assetType: "Equity", price: 145, marketCap: 400e9, peRatio: 30, grossMargin: 0.71, operatingMargin: 0.3, profitMargin: 0.2, revenueTTM: 55e9, revenueGrowthYoY: 0.08, dividendYield: 0.011, beta: 1.0, asOf: "static reference" },
  ADBE: { name: "Adobe Inc.", sector: "Technology", industry: "Software - Application", assetType: "Equity", price: 400, marketCap: 175e9, peRatio: 25, grossMargin: 0.89, operatingMargin: 0.34, profitMargin: 0.28, revenueTTM: 22e9, revenueGrowthYoY: 0.1, dividendYield: 0, beta: 1.1, asOf: "static reference" },
  INTC: { name: "Intel Corp.", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 24, marketCap: 105e9, peRatio: null, grossMargin: 0.32, operatingMargin: -0.05, profitMargin: -0.1, revenueTTM: 53e9, revenueGrowthYoY: -0.02, dividendYield: 0, beta: 1.1, asOf: "static reference" },
  CSCO: { name: "Cisco Systems Inc.", sector: "Technology", industry: "Communication Equipment", assetType: "Equity", price: 58, marketCap: 230e9, peRatio: 22, grossMargin: 0.64, operatingMargin: 0.26, profitMargin: 0.2, revenueTTM: 55e9, revenueGrowthYoY: 0.05, dividendYield: 0.025, beta: 0.85, asOf: "static reference" },

  JPM: { name: "JPMorgan Chase & Co.", sector: "Financial Services", industry: "Banks - Diversified", assetType: "Equity", price: 235, marketCap: 660e9, peRatio: 13, grossMargin: null, operatingMargin: 0.42, profitMargin: 0.34, revenueTTM: 165e9, revenueGrowthYoY: 0.1, dividendYield: 0.021, beta: 1.1, asOf: "static reference" },
  BAC: { name: "Bank of America Corp.", sector: "Financial Services", industry: "Banks - Diversified", assetType: "Equity", price: 62.685, marketCap: 438340533750, peRatio: 14.43, grossMargin: null, operatingMargin: null, profitMargin: 0.2698, revenueTTM: 113097000000, revenueGrowthYoY: 0.11, dividendYield: 0.0179, beta: 1.25, asOf: "static reference" },
  WFC: { name: "Wells Fargo & Co.", sector: "Financial Services", industry: "Banks - Diversified", assetType: "Equity", price: 72, marketCap: 240e9, peRatio: 13, grossMargin: null, operatingMargin: 0.33, profitMargin: 0.26, revenueTTM: 82e9, revenueGrowthYoY: 0.03, dividendYield: 0.022, beta: 1.1, asOf: "static reference" },
  GS: { name: "Goldman Sachs Group", sector: "Financial Services", industry: "Capital Markets", assetType: "Equity", price: 560, marketCap: 185e9, peRatio: 15, grossMargin: null, operatingMargin: 0.38, profitMargin: 0.28, revenueTTM: 53e9, revenueGrowthYoY: 0.15, dividendYield: 0.02, beta: 1.3, asOf: "static reference" },
  V: { name: "Visa Inc.", sector: "Financial Services", industry: "Credit Services", assetType: "Equity", price: 310, marketCap: 610e9, peRatio: 30, grossMargin: 0.97, operatingMargin: 0.67, profitMargin: 0.53, revenueTTM: 36e9, revenueGrowthYoY: 0.1, dividendYield: 0.007, beta: 0.95, asOf: "static reference" },
  MA: { name: "Mastercard Inc.", sector: "Financial Services", industry: "Credit Services", assetType: "Equity", price: 520, marketCap: 480e9, peRatio: 34, grossMargin: 0.76, operatingMargin: 0.58, profitMargin: 0.46, revenueTTM: 28e9, revenueGrowthYoY: 0.12, dividendYield: 0.005, beta: 1.05, asOf: "static reference" },
  BRK: { name: "Berkshire Hathaway", sector: "Financial Services", industry: "Insurance - Diversified", assetType: "Equity", price: 470, marketCap: 1.0e12, peRatio: 12, grossMargin: null, operatingMargin: 0.2, profitMargin: 0.18, revenueTTM: 370e9, revenueGrowthYoY: 0.03, dividendYield: 0, beta: 0.85, asOf: "static reference" },

  UNH: { name: "UnitedHealth Group", sector: "Healthcare", industry: "Healthcare Plans", assetType: "Equity", price: 340, marketCap: 310e9, peRatio: 14, grossMargin: 0.24, operatingMargin: 0.07, profitMargin: 0.04, revenueTTM: 400e9, revenueGrowthYoY: 0.07, dividendYield: 0.024, beta: 0.6, asOf: "static reference" },
  JNJ: { name: "Johnson & Johnson", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "Equity", price: 160, marketCap: 385e9, peRatio: 16, grossMargin: 0.68, operatingMargin: 0.24, profitMargin: 0.2, revenueTTM: 89e9, revenueGrowthYoY: 0.04, dividendYield: 0.032, beta: 0.5, asOf: "static reference" },
  LLY: { name: "Eli Lilly and Co.", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "Equity", price: 850, marketCap: 800e9, peRatio: 55, grossMargin: 0.81, operatingMargin: 0.35, profitMargin: 0.28, revenueTTM: 50e9, revenueGrowthYoY: 0.35, dividendYield: 0.007, beta: 0.4, asOf: "static reference" },
  PFE: { name: "Pfizer Inc.", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "Equity", price: 26, marketCap: 150e9, peRatio: 14, grossMargin: 0.65, operatingMargin: 0.15, profitMargin: 0.1, revenueTTM: 60e9, revenueGrowthYoY: -0.03, dividendYield: 0.065, beta: 0.55, asOf: "static reference" },
  ABBV: { name: "AbbVie Inc.", sector: "Healthcare", industry: "Drug Manufacturers - General", assetType: "Equity", price: 190, marketCap: 335e9, peRatio: 32, grossMargin: 0.7, operatingMargin: 0.28, profitMargin: 0.15, revenueTTM: 56e9, revenueGrowthYoY: 0.05, dividendYield: 0.033, beta: 0.6, asOf: "static reference" },

  WMT: { name: "Walmart Inc.", sector: "Consumer Defensive", industry: "Discount Stores", assetType: "Equity", price: 90, marketCap: 725e9, peRatio: 38, grossMargin: 0.25, operatingMargin: 0.045, profitMargin: 0.03, revenueTTM: 680e9, revenueGrowthYoY: 0.06, dividendYield: 0.009, beta: 0.5, asOf: "static reference" },
  COST: { name: "Costco Wholesale Corp.", sector: "Consumer Defensive", industry: "Discount Stores", assetType: "Equity", price: 950, marketCap: 420e9, peRatio: 52, grossMargin: 0.13, operatingMargin: 0.036, profitMargin: 0.027, revenueTTM: 265e9, revenueGrowthYoY: 0.07, dividendYield: 0.005, beta: 0.75, asOf: "static reference" },
  PG: { name: "Procter & Gamble", sector: "Consumer Defensive", industry: "Household & Personal Products", assetType: "Equity", price: 165, marketCap: 390e9, peRatio: 25, grossMargin: 0.52, operatingMargin: 0.23, profitMargin: 0.18, revenueTTM: 84e9, revenueGrowthYoY: 0.03, dividendYield: 0.024, beta: 0.4, asOf: "static reference" },
  KO: { name: "Coca-Cola Co.", sector: "Consumer Defensive", industry: "Beverages - Non-Alcoholic", assetType: "Equity", price: 88.07, marketCap: 378925578500, peRatio: 26.53, grossMargin: 0.6162, operatingMargin: null, profitMargin: 0.2734, revenueTTM: 47941000000, revenueGrowthYoY: 0.0187, dividendYield: 0.0236, beta: 0.55, asOf: "static reference" },
  PEP: { name: "PepsiCo Inc.", sector: "Consumer Defensive", industry: "Beverages - Non-Alcoholic", assetType: "Equity", price: 150, marketCap: 205e9, peRatio: 20, grossMargin: 0.55, operatingMargin: 0.14, profitMargin: 0.1, revenueTTM: 92e9, revenueGrowthYoY: 0.02, dividendYield: 0.036, beta: 0.5, asOf: "static reference" },
  MCD: { name: "McDonald's Corp.", sector: "Consumer Cyclical", industry: "Restaurants", assetType: "Equity", price: 300, marketCap: 215e9, peRatio: 25, grossMargin: 0.57, operatingMargin: 0.46, profitMargin: 0.33, revenueTTM: 26e9, revenueGrowthYoY: 0.03, dividendYield: 0.023, beta: 0.6, asOf: "static reference" },
  NKE: { name: "Nike Inc.", sector: "Consumer Cyclical", industry: "Footwear & Accessories", assetType: "Equity", price: 75, marketCap: 110e9, peRatio: 24, grossMargin: 0.44, operatingMargin: 0.08, profitMargin: 0.06, revenueTTM: 47e9, revenueGrowthYoY: -0.05, dividendYield: 0.019, beta: 1.05, asOf: "static reference" },
  SBUX: { name: "Starbucks Corp.", sector: "Consumer Cyclical", industry: "Restaurants", assetType: "Equity", price: 104.45, marketCap: 119073000000, peRatio: 60.24, grossMargin: null, operatingMargin: null, profitMargin: 0.0499, revenueTTM: 37184400000, revenueGrowthYoY: 0.0279, dividendYield: 0.0237, beta: 0.9, asOf: "static reference" },
  HD: { name: "Home Depot Inc.", sector: "Consumer Cyclical", industry: "Home Improvement Retail", assetType: "Equity", price: 320.995, marketCap: 320253501550, peRatio: 22.47, grossMargin: 0.3332, operatingMargin: null, profitMargin: 0.086, revenueTTM: 164683000000, revenueGrowthYoY: 0.0324, dividendYield: 0.0288, beta: 1.0, asOf: "static reference" },

  XOM: { name: "Exxon Mobil Corp.", sector: "Energy", industry: "Oil & Gas Integrated", assetType: "Equity", price: 115, marketCap: 500e9, peRatio: 14, grossMargin: null, operatingMargin: 0.14, profitMargin: 0.1, revenueTTM: 340e9, revenueGrowthYoY: -0.02, dividendYield: 0.033, beta: 0.9, asOf: "static reference" },
  CVX: { name: "Chevron Corp.", sector: "Energy", industry: "Oil & Gas Integrated", assetType: "Equity", price: 160, marketCap: 300e9, peRatio: 15, grossMargin: null, operatingMargin: 0.12, profitMargin: 0.09, revenueTTM: 195e9, revenueGrowthYoY: -0.03, dividendYield: 0.041, beta: 1.0, asOf: "static reference" },

  BA: { name: "Boeing Co.", sector: "Industrials", industry: "Aerospace & Defense", assetType: "Equity", price: 175, marketCap: 130e9, peRatio: null, grossMargin: 0.1, operatingMargin: -0.08, profitMargin: -0.1, revenueTTM: 68e9, revenueGrowthYoY: 0.1, dividendYield: 0, beta: 1.4, asOf: "static reference" },
  CAT: { name: "Caterpillar Inc.", sector: "Industrials", industry: "Farm & Heavy Construction Machinery", assetType: "Equity", price: 400, marketCap: 195e9, peRatio: 18, grossMargin: 0.34, operatingMargin: 0.2, profitMargin: 0.15, revenueTTM: 63e9, revenueGrowthYoY: 0.0, dividendYield: 0.015, beta: 1.1, asOf: "static reference" },
  GE: { name: "GE Aerospace", sector: "Industrials", industry: "Aerospace & Defense", assetType: "Equity", price: 337.02, marketCap: 349679325270, peRatio: 39.74, grossMargin: null, operatingMargin: null, profitMargin: 0.1898, revenueTTM: 45855000000, revenueGrowthYoY: 0.1848, dividendYield: 0.0049, beta: 1.2, asOf: "static reference" },

  PLTR: { name: "Palantir Technologies", sector: "Technology", industry: "Software - Infrastructure", assetType: "Equity", price: 174.31, marketCap: 418883161519, peRatio: 148.99, grossMargin: 0.8237, operatingMargin: null, profitMargin: 0.3631, revenueTTM: 4475446000, revenueGrowthYoY: 0.5619, dividendYield: 0, beta: 2.5, asOf: "static reference" },
  UBER: { name: "Uber Technologies", sector: "Technology", industry: "Software - Application", assetType: "Equity", price: 75, marketCap: 155e9, peRatio: 15, grossMargin: 0.39, operatingMargin: 0.07, profitMargin: 0.2, revenueTTM: 44e9, revenueGrowthYoY: 0.16, dividendYield: 0, beta: 1.4, asOf: "static reference" },
  SHOP: { name: "Shopify Inc.", sector: "Technology", industry: "Software - Application", assetType: "Equity", price: 80, marketCap: 100e9, peRatio: 65, grossMargin: 0.51, operatingMargin: 0.1, profitMargin: 0.08, revenueTTM: 8.9e9, revenueGrowthYoY: 0.25, dividendYield: 0, beta: 2.2, asOf: "static reference" },
  SQ: { name: "Block Inc.", sector: "Technology", industry: "Software - Infrastructure", assetType: "Equity", price: 70, marketCap: 40e9, peRatio: 20, grossMargin: 0.38, operatingMargin: 0.06, profitMargin: 0.05, revenueTTM: 24e9, revenueGrowthYoY: 0.05, dividendYield: 0, beta: 2.4, asOf: "static reference" },
  PYPL: { name: "PayPal Holdings", sector: "Financial Services", industry: "Credit Services", assetType: "Equity", price: 70, marketCap: 68e9, peRatio: 15, grossMargin: 0.46, operatingMargin: 0.18, profitMargin: 0.14, revenueTTM: 32e9, revenueGrowthYoY: 0.06, dividendYield: 0, beta: 1.4, asOf: "static reference" },
  COIN: { name: "Coinbase Global", sector: "Financial Services", industry: "Capital Markets", assetType: "Equity", price: 250, marketCap: 62e9, peRatio: 30, grossMargin: 0.85, operatingMargin: 0.25, profitMargin: 0.3, revenueTTM: 6.5e9, revenueGrowthYoY: 0.4, dividendYield: 0, beta: 3.5, asOf: "static reference" },
  SOFI: { name: "SoFi Technologies", sector: "Financial Services", industry: "Credit Services", assetType: "Equity", price: 15, marketCap: 16e9, peRatio: 35, grossMargin: 0.6, operatingMargin: 0.08, profitMargin: 0.07, revenueTTM: 2.7e9, revenueGrowthYoY: 0.25, dividendYield: 0, beta: 1.9, asOf: "static reference" },

  DIS: { name: "Walt Disney Co.", sector: "Communication Services", industry: "Entertainment", assetType: "Equity", price: 105.29, marketCap: 181803190100, peRatio: 21.72, grossMargin: null, operatingMargin: null, profitMargin: 0.1314, revenueTTM: 94425000000, revenueGrowthYoY: 0.0335, dividendYield: 0.0142, beta: 1.2, asOf: "static reference" },
  T: { name: "AT&T Inc.", sector: "Communication Services", industry: "Telecom Services", assetType: "Equity", price: 24, marketCap: 175e9, peRatio: 13, grossMargin: 0.6, operatingMargin: 0.18, profitMargin: 0.1, revenueTTM: 122e9, revenueGrowthYoY: 0.01, dividendYield: 0.045, beta: 0.6, asOf: "static reference" },

  QCOM: { name: "Qualcomm Inc.", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 165, marketCap: 185e9, peRatio: 18, grossMargin: 0.56, operatingMargin: 0.3, profitMargin: 0.25, revenueTTM: 39e9, revenueGrowthYoY: 0.1, dividendYield: 0.02, beta: 1.3, asOf: "static reference" },
  TXN: { name: "Texas Instruments", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 200, marketCap: 180e9, peRatio: 32, grossMargin: 0.58, operatingMargin: 0.35, profitMargin: 0.3, revenueTTM: 16.5e9, revenueGrowthYoY: 0.08, dividendYield: 0.026, beta: 1.0, asOf: "static reference" },
  MU: { name: "Micron Technology", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 1014.95, marketCap: 1146277460620, peRatio: 23.01, grossMargin: 0.3979, operatingMargin: null, profitMargin: 0.2284, revenueTTM: 37378000000, revenueGrowthYoY: 0.4885, dividendYield: 0.0005, beta: 1.6, asOf: "static reference" },
  IBM: { name: "IBM Corp.", sector: "Technology", industry: "Information Technology Services", assetType: "Equity", price: 230, marketCap: 210e9, peRatio: 28, grossMargin: 0.56, operatingMargin: 0.17, profitMargin: 0.12, revenueTTM: 62e9, revenueGrowthYoY: 0.03, dividendYield: 0.03, beta: 0.7, asOf: "static reference" },

  RIVN: { name: "Rivian Automotive", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "Equity", price: 14, marketCap: 14e9, peRatio: null, grossMargin: -0.05, operatingMargin: -0.5, profitMargin: -0.55, revenueTTM: 5.2e9, revenueGrowthYoY: 0.1, dividendYield: 0, beta: 2.0, asOf: "static reference" },
  F: { name: "Ford Motor Co.", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "Equity", price: 11, marketCap: 43e9, peRatio: 9, grossMargin: 0.08, operatingMargin: 0.03, profitMargin: 0.015, revenueTTM: 180e9, revenueGrowthYoY: 0.03, dividendYield: 0.055, beta: 1.4, asOf: "static reference" },
  GM: { name: "General Motors Co.", sector: "Consumer Cyclical", industry: "Auto Manufacturers", assetType: "Equity", price: 55, marketCap: 55e9, peRatio: 6, grossMargin: 0.12, operatingMargin: 0.08, profitMargin: 0.06, revenueTTM: 185e9, revenueGrowthYoY: 0.02, dividendYield: 0.01, beta: 1.5, asOf: "static reference" },

  // Broad-market / sector ETFs — top holdings are approximate, for overlap detection only.
  VOO: { name: "Vanguard S&P 500 ETF", sector: "Diversified", industry: "Large Blend ETF", assetType: "ETF", price: 560, marketCap: null, peRatio: 26, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.012, beta: 1.0, topHoldings: ["AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "AVGO", "TSLA", "BRK"], asOf: "static reference" },
  SPY: { name: "SPDR S&P 500 ETF Trust", sector: "Diversified", industry: "Large Blend ETF", assetType: "ETF", price: 770.23, marketCap: 814273381207, peRatio: 26.08, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0103, beta: 1.0, topHoldings: ["AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "AVGO", "TSLA", "BRK"], asOf: "static reference" },
  IVV: { name: "iShares Core S&P 500 ETF", sector: "Diversified", industry: "Large Blend ETF", assetType: "ETF", price: 570, marketCap: null, peRatio: 26, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.012, beta: 1.0, topHoldings: ["AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "AVGO", "TSLA", "BRK"], asOf: "static reference" },
  VTI: { name: "Vanguard Total Stock Market ETF", sector: "Diversified", industry: "Total Market ETF", assetType: "ETF", price: 379.73, marketCap: 693583437872, peRatio: 28.67, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0104, beta: 1.0, topHoldings: ["AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "AVGO", "TSLA", "BRK"], asOf: "static reference" },
  QQQ: { name: "Invesco QQQ Trust (Nasdaq-100)", sector: "Diversified", industry: "Large Growth ETF", assetType: "ETF", price: 719.06, marketCap: 490578685000, peRatio: 34.24, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0054, beta: 1.1, topHoldings: ["AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "AVGO", "TSLA", "COST"], asOf: "static reference" },
  VUG: { name: "Vanguard Growth ETF", sector: "Diversified", industry: "Large Growth ETF", assetType: "ETF", price: 400, marketCap: null, peRatio: 31, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.005, beta: 1.1, topHoldings: ["AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "AVGO", "TSLA", "LLY"], asOf: "static reference" },
  SCHD: { name: "Schwab US Dividend Equity ETF", sector: "Diversified", industry: "Dividend Value ETF", assetType: "ETF", price: 34.795, marketCap: 112391329500, peRatio: 18.32, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.031, beta: 0.8, topHoldings: ["PFE", "CVX", "KO", "PEP", "T", "XOM"], asOf: "static reference" },
  VYM: { name: "Vanguard High Dividend Yield ETF", sector: "Diversified", industry: "Dividend Value ETF", assetType: "ETF", price: 135, marketCap: null, peRatio: 17, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.028, beta: 0.85, topHoldings: ["JPM", "XOM", "JNJ", "PG", "CVX", "KO"], asOf: "static reference" },
  DIA: { name: "SPDR Dow Jones Industrial Average ETF", sector: "Diversified", industry: "Large Blend ETF", assetType: "ETF", price: 420, marketCap: null, peRatio: 24, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.018, beta: 0.95, topHoldings: ["GS", "MSFT", "CAT", "V", "HD", "MCD"], asOf: "static reference" },
  ARKK: { name: "ARK Innovation ETF", sector: "Diversified", industry: "Growth / Thematic ETF", assetType: "ETF", price: 55, marketCap: null, peRatio: null, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0, beta: 1.8, topHoldings: ["TSLA", "COIN", "ROKU", "SHOP", "RBLX"], asOf: "static reference" },
  XLK: { name: "Technology Select Sector SPDR", sector: "Technology", industry: "Technology Sector ETF", assetType: "ETF", price: 240, marketCap: null, peRatio: 32, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.007, beta: 1.1, topHoldings: ["AAPL", "MSFT", "NVDA", "AVGO", "CRM", "ORCL"], asOf: "static reference" },
  XLF: { name: "Financial Select Sector SPDR", sector: "Financial Services", industry: "Financial Sector ETF", assetType: "ETF", price: 58.1, marketCap: 55011719309, peRatio: 16.93, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0143, beta: 1.1, topHoldings: ["JPM", "BRK", "V", "MA", "BAC", "GS", "WFC"], asOf: "static reference" },

  // Additional tickers pulled in from a real brokerage import.
  DAL: { name: "Delta Air Lines Inc.", sector: "Industrials", industry: "Airlines", assetType: "Equity", price: 80.155, marketCap: 52711771565, peRatio: 13.32, grossMargin: null, operatingMargin: null, profitMargin: 0.079, revenueTTM: 63364000000, revenueGrowthYoY: 0.0279, dividendYield: 0.0097, beta: 1.3, asOf: "static reference" },
  LUV: { name: "Southwest Airlines Co.", sector: "Industrials", industry: "Airlines", assetType: "Equity", price: 39.605, marketCap: 19375090172, peRatio: 24.04, grossMargin: null, operatingMargin: null, profitMargin: 0.0157, revenueTTM: 28063000000, revenueGrowthYoY: 0.0211, dividendYield: 0.0182, beta: 1.2, asOf: "static reference" },
  SRFM: { name: "Surf Air Mobility Inc.", sector: "Industrials", industry: "Airlines", assetType: "Equity", price: 0.6633, marketCap: 82429410, peRatio: null, grossMargin: null, operatingMargin: null, profitMargin: -1.0375, revenueTTM: 106557000, revenueGrowthYoY: -0.1077, dividendYield: 0, beta: 2.2, asOf: "static reference" },
  GEV: { name: "GE Vernova Inc.", sector: "Industrials", industry: "Electrical Equipment & Parts", assetType: "Equity", price: 941.925, marketCap: 250866276180, peRatio: 26.96, grossMargin: 0.1979, operatingMargin: null, profitMargin: 0.1283, revenueTTM: 38068000000, revenueGrowthYoY: 0.0897, dividendYield: 0.0019, beta: 1.3, asOf: "static reference" },
  ACHR: { name: "Archer Aviation Inc.", sector: "Industrials", industry: "Aerospace & Defense", assetType: "Equity", price: 5.72, marketCap: 4404537280, peRatio: null, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0, beta: 2.3, asOf: "static reference" },
  JOBY: { name: "Joby Aviation Inc.", sector: "Industrials", industry: "Aerospace & Defense", assetType: "Equity", price: 6.75, marketCap: 6676588695, peRatio: null, grossMargin: 0.451, operatingMargin: null, profitMargin: null, revenueTTM: 53425000, revenueGrowthYoY: null, dividendYield: 0, beta: 2.3, asOf: "static reference" },
  SHLS: { name: "Shoals Technologies Group Inc.", sector: "Industrials", industry: "Electrical Equipment & Parts", assetType: "Equity", price: 7.12, marketCap: 1198296000, peRatio: 37.95, grossMargin: 0.3503, operatingMargin: null, profitMargin: 0.0706, revenueTTM: 475331000, revenueGrowthYoY: 0.1907, dividendYield: 0, beta: 1.9, asOf: "static reference" },
  PLUG: { name: "Plug Power Inc.", sector: "Industrials", industry: "Electrical Equipment & Parts", assetType: "Equity", price: 2.165, marketCap: 3024938000, peRatio: null, grossMargin: -0.341, operatingMargin: null, profitMargin: -2.2983, revenueTTM: 709919000, revenueGrowthYoY: 0.129, dividendYield: 0, beta: 2.0, asOf: "static reference" },

  NXPI: { name: "NXP Semiconductors N.V.", sector: "Technology", industry: "Semiconductors", assetType: "Equity", price: 227.85, marketCap: 57455607381, peRatio: 19.34, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0178, beta: 1.2, asOf: "static reference" },
  QBTS: { name: "D-Wave Quantum Inc.", sector: "Technology", industry: "Computer Hardware", assetType: "Equity", price: 16.58, marketCap: 6175056792, peRatio: null, grossMargin: 0.8259, operatingMargin: null, profitMargin: -14.441, revenueTTM: 24587000, revenueGrowthYoY: 1.7851, dividendYield: 0, beta: 2.8, asOf: "static reference" },
  RR: { name: "Richtech Robotics Inc.", sector: "Technology", industry: "Robotics & Automation", assetType: "Equity", price: 1.7442, marketCap: 392622819, peRatio: null, grossMargin: 0.3588, operatingMargin: null, profitMargin: -9.7273, revenueTTM: 5045000, revenueGrowthYoY: -0.424, dividendYield: 0, beta: 2.6, asOf: "static reference" },

  TGTX: { name: "TG Therapeutics Inc.", sector: "Healthcare", industry: "Biotechnology", assetType: "Equity", price: 55.99, marketCap: 8570335749, peRatio: 20.39, grossMargin: 0.8365, operatingMargin: null, profitMargin: 0.7256, revenueTTM: 616287000, revenueGrowthYoY: 0.8732, dividendYield: 0, beta: 1.5, asOf: "static reference" },
  ISRG: { name: "Intuitive Surgical Inc.", sector: "Healthcare", industry: "Medical Devices", assetType: "Equity", price: 366.67, marketCap: 129536456297, peRatio: 42.03, grossMargin: 0.66, operatingMargin: null, profitMargin: 0.2838, revenueTTM: 10064700000, revenueGrowthYoY: 0.2051, dividendYield: 0, beta: 0.9, asOf: "static reference" },
  MDLN: { name: "Medline Inc.", sector: "Healthcare", industry: "Medical Distribution", assetType: "Equity", price: 36.59, marketCap: 48105146538, peRatio: 42.91, grossMargin: 0.2644, operatingMargin: null, profitMargin: 0.0408, revenueTTM: 28432000000, revenueGrowthYoY: null, dividendYield: 0, beta: 1.0, asOf: "static reference" },

  C: { name: "Citigroup Inc.", sector: "Financial Services", industry: "Banks - Diversified", assetType: "Equity", price: 137.73, marketCap: 231033811200, peRatio: 14.87, grossMargin: null, operatingMargin: null, profitMargin: 0.1679, revenueTTM: 85225000000, revenueGrowthYoY: 0.0504, dividendYield: 0.0179, beta: 1.4, asOf: "static reference" },
  OPEN: { name: "Opendoor Technologies Inc.", sector: "Real Estate", industry: "Real Estate Services", assetType: "Equity", price: 3.145, marketCap: 3054081510, peRatio: null, grossMargin: 0.0801, operatingMargin: null, profitMargin: -0.2974, revenueTTM: 4371000000, revenueGrowthYoY: -0.1518, dividendYield: 0, beta: 2.4, asOf: "static reference" },

  SE: { name: "Sea Ltd.", sector: "Consumer Cyclical", industry: "Internet Retail", assetType: "Equity", price: 112.135, marketCap: 68680950948, peRatio: 42.43, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0, beta: 1.8, asOf: "static reference" },
  LKNCY: { name: "Luckin Coffee Inc.", sector: "Consumer Defensive", industry: "Restaurants", assetType: "Equity", price: 34.81, marketCap: 9983132670, peRatio: 20.67, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0, beta: 1.4, asOf: "static reference" },

  ARQ: { name: "Arq Inc.", sector: "Basic Materials", industry: "Specialty Chemicals", assetType: "Equity", price: 2.3, marketCap: 100437550, peRatio: null, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0, beta: 1.8, asOf: "static reference" },
  OKLO: { name: "Oklo Inc.", sector: "Energy", industry: "Nuclear / Utilities", assetType: "Equity", price: 41.285, marketCap: 7679753130, peRatio: null, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0, beta: 2.0, asOf: "static reference" },
  SPCX: { name: "Space Exploration Technologies Corp.", sector: "Communication Services", industry: "Telecom Services", assetType: "Equity", price: 147.99, marketCap: 2008382616988, peRatio: null, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0, beta: 1.6, asOf: "static reference" },

  // ETFs / funds — topHoldings are approximate, for overlap detection only.
  RSP: { name: "Invesco S&P 500 Equal Weight ETF", sector: "Diversified", industry: "Large Blend ETF", assetType: "ETF", price: 219.01, marketCap: 100418858324, peRatio: 21.39, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0161, beta: 1.0, topHoldings: ["AAPL", "MSFT", "NVDA", "AMD", "TSLA", "BAC", "KO", "GE", "HD", "DIS"], asOf: "static reference" },
  FNCL: { name: "Fidelity MSCI Financials Index ETF", sector: "Diversified", industry: "Financial Sector ETF", assetType: "ETF", price: 82.715, marketCap: 2411142250, peRatio: 16.29, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0158, beta: 1.1, topHoldings: ["JPM", "BAC", "WFC", "GS", "C"], asOf: "static reference" },
  VGT: { name: "Vanguard Information Technology ETF", sector: "Diversified", industry: "Technology Sector ETF", assetType: "ETF", price: 121.25, marketCap: 148572389034, peRatio: 38.39, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0041, beta: 1.1, topHoldings: ["AAPL", "MSFT", "NVDA", "AVGO", "ORCL"], asOf: "static reference" },
  IGV: { name: "iShares Expanded Tech-Software ETF", sector: "Diversified", industry: "Software ETF", assetType: "ETF", price: 104.625, marketCap: 14176687500, peRatio: 59.07, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0026, beta: 1.2, topHoldings: ["MSFT", "ORCL", "CRM", "PLTR", "ADBE"], asOf: "static reference" },
  BOTZ: { name: "Global X Robotics & AI ETF", sector: "Diversified", industry: "Robotics & AI ETF", assetType: "ETF", price: 35.895, marketCap: 3421337663, peRatio: 61.21, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.006, beta: 1.3, topHoldings: ["NVDA", "ISRG"], asOf: "static reference" },
  XAR: { name: "SPDR S&P Aerospace & Defense ETF", sector: "Diversified", industry: "Aerospace & Defense ETF", assetType: "ETF", price: 253.02, marketCap: 5686624500, peRatio: 88.33, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0048, beta: 1.1, topHoldings: ["GE", "BA", "NOC", "LMT"], asOf: "static reference" },
  JETS: { name: "U.S. Global Jets ETF", sector: "Diversified", industry: "Airlines ETF", assetType: "ETF", price: 28.82, marketCap: 747879000, peRatio: 19.86, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0084, beta: 1.4, topHoldings: ["DAL", "LUV", "UAL", "AAL"], asOf: "static reference" },
  LIT: { name: "Global X Lithium & Battery Tech ETF", sector: "Diversified", industry: "Thematic ETF", assetType: "ETF", price: 74.14, marketCap: 1590725266, peRatio: 31.71, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0101, beta: 1.3, asOf: "static reference" },
  UCO: { name: "ProShares Ultra Bloomberg Crude Oil", sector: "Diversified", industry: "Leveraged Commodity ETN", assetType: "ETF", price: 47.4953, marketCap: 434254277, peRatio: null, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0, beta: 2.5, asOf: "static reference" },
  GAMR: { name: "VanEck Video Gaming and eSports ETF", sector: "Diversified", industry: "Gaming ETF", assetType: "ETF", price: 97.7901, marketCap: 40093941, peRatio: 32.59, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0078, beta: 1.4, asOf: "static reference" },
  RACK: { name: "Global X Data Center & Digital Infrastructure ETF", sector: "Diversified", industry: "Data Center ETF", assetType: "ETF", price: 49.04, marketCap: 63752000, peRatio: 40.57, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0.0062, beta: 1.2, asOf: "static reference" },
  RVI: { name: "Frontier private-companies closed-end fund (RVI)", sector: "Diversified", industry: "Closed-End Fund", assetType: "ETF", price: 27.315, marketCap: 744257678, peRatio: null, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0, beta: 1.5, asOf: "static reference" },
  RVII: { name: "Y Combinator-linked venture BDC (RVII)", sector: "Diversified", industry: "Business Development Company", assetType: "ETF", price: 25.0001, marketCap: 226660507, peRatio: null, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0, beta: 1.6, asOf: "static reference" },
  GBTC: { name: "Grayscale Bitcoin Trust", sector: "Diversified", industry: "Digital Assets Trust", assetType: "ETF", price: 61.75, marketCap: 10357333675, peRatio: null, grossMargin: null, operatingMargin: null, profitMargin: null, revenueTTM: null, revenueGrowthYoY: null, dividendYield: 0, beta: 3.0, asOf: "static reference" },
};

export function getFallbackFundamentals(ticker: string): Fundamentals | null {
  const entry = FALLBACK_FUNDAMENTALS[ticker.toUpperCase()];
  if (!entry) return null;
  return { ticker: ticker.toUpperCase(), source: "fallback", ...entry };
}
